version: '3.5'
services:
  zk:
    image: 'confluentinc/cp-zookeeper:6.1.1'
    hostname: zk
    restart: always
    container_name: zk
    networks:
      - confluent
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 4000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 'zk:2888:3888'

  kafka:
    image: 'confluentinc/cp-enterprise-kafka:6.1.1'
    hostname: kafka
    restart: always
    container_name: kafka
    networks:
      - confluent
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: 'zk:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT'
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG4J_LOGGERS: "kafka.log=WARN,kafka.cluster=WARN,kafka.coordinator=WARN,kafka.controller=WARN,kafka.server=WARN,state.change.logger=WARN"

  schema-registry:
    image: 'confluentinc/cp-schema-registry:6.1.1'
    hostname: schema-registry
    container_name: schema-registry
    networks:
      - confluent
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
      SCHEMA_REGISTRY_LISTENERS: 'http://schema-registry:8081'

  connect:
    build: ./kafka-connect/.
    hostname: connect
    restart: always
    container_name: connect
    ports:
      - 8083:8083
      - 7071:7071
    volumes:
      # Use if you want to activate gcp connector
      # need serviceaccount.json file inside ./config/gcp/
      - ./config/gcp/:/etc/config/secret/
    networks:
      - confluent
    environment:
      CONNECT_KAFKA_HEAP_OPTS: "-Xms1g -Xmx3g"
      KAFKA_HEAP_OPTS: "-Xms1g -Xmx3g"
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: "connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
      CONNECT_REST_HOST_NAME: "connect"
      CONNECT_REST_PORT: 8083
      CONNECT_CUB_KAFKA_TIMEOUT: 60
      CONNECT_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: "All"
      CONNECT_TOPIC_CREATION_ENABLE: "true"
      CONNECT_KEY_CONVERTER_AUTO_REGISTRY_SCHEMAS: "true"
      CONNECT_VALUE_CONVERTER_AUTO_REGISTRY_SCHEMAS: "true"
      #      CONNECT_TOPIC_CREATION_ENABLE: "false"
      #      CONNECT_KEY_CONVERTER_AUTO_REGISTRY_SCHEMAS: "false"
      #      CONNECT_VALUE_CONVERTER_AUTO_REGISTRY_SCHEMAS: "false"

  akhq:
    image: tchiotludo/akhq:latest
    hostname: akhq
    restart: always
    container_name: akhq
    networks:
      - confluent
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            server:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8081"
              connect:
                - name: connect
                  url: "http://connect:8083"
    ports:
      - 8080:8080
       
networks:
  confluent: